var qfilename = new Array();
var ix = 0;
qfilename[ix] = "fuzzy-concept.html";
ix++;
qfilename[ix] = "i-must-study-politics-and-war.html";
ix++;
qfilename[ix] = "a-dark-procession.html";
ix++;
qfilename[ix] = "merely-thoroughly-outrageous.html";
ix++;
qfilename[ix] = "occasions-when-the-intellect-retires-gracefully.html";
ix++;
qfilename[ix] = "the-only-sign-of-mental-activity.html";
ix++;
qfilename[ix] = "we-dont-even-own-suits.html";
ix++;
qfilename[ix] = "model-ii-decision-making.html";
ix++;
qfilename[ix] = "model-ii-values.html";
ix++;
qfilename[ix] = "entertain-a-thought.html";
ix++;
qfilename[ix] = "the-four-fold-way.html";
ix++;
qfilename[ix] = "the-cult-of-ignorance.html";
ix++;
qfilename[ix] = "cockpits-with-instruments-controlled-by-gremlins.html";
ix++;
qfilename[ix] = "we-need-a-place-to-stand.html";
ix++;
qfilename[ix] = "careful-thoughtful-small-practical-efforts.html";
ix++;
qfilename[ix] = "any-love-for-justice.html";
ix++;
qfilename[ix] = "ancient-ethnic-sores-belching-fire.html";
ix++;
qfilename[ix] = "our-reply-to-violence.html";
ix++;
qfilename[ix] = "seeing-the-bigger-picture-from-multiple-angles.html";
ix++;
qfilename[ix] = "art-science-and-empire.html";
ix++;
qfilename[ix] = "expectations-of-holiness.html";
ix++;
qfilename[ix] = "minute-particulars.html";
ix++;
qfilename[ix] = "to-see-a-world-in-a-grain-of-sand.html";
ix++;
qfilename[ix] = "cost-of-education.html";
ix++;
qfilename[ix] = "having-fewer-children-and-grandchildren.html";
ix++;
qfilename[ix] = "the-tautness-of-this-resonant-connection.html";
ix++;
qfilename[ix] = "chaos-and-mediocrity.html";
ix++;
qfilename[ix] = "counter-cultures-own-values-and-aesthetics-decayed.html";
ix++;
qfilename[ix] = "history-as-postmodern-collage.html";
ix++;
qfilename[ix] = "little-i-recognized-as-music.html";
ix++;
qfilename[ix] = "never-knew-cocaine-to-improve-anything.html";
ix++;
qfilename[ix] = "records-we-made-together-in-the-sixties.html";
ix++;
qfilename[ix] = "sixties-surpluses-of-money-and-time.html";
ix++;
qfilename[ix] = "people-ask-me-to-predict-the-future.html";
ix++;
qfilename[ix] = "art-is-a-hammer.html";
ix++;
qfilename[ix] = "nirvana-antipattern.html";
ix++;
qfilename[ix] = "two-ideas-of-government.html";
ix++;
qfilename[ix] = "between-saturday-night-and-sunday-morning.html";
ix++;
qfilename[ix] = "an-invincible-summer.html";
ix++;
qfilename[ix] = "work-soul-and-life.html";
ix++;
qfilename[ix] = "six-impossible-things-before-breakfast.html";
ix++;
qfilename[ix] = "a-mind-is-blown.html";
ix++;
qfilename[ix] = "down-these-mean-streets.html";
ix++;
qfilename[ix] = "vital-and-significant-forms-of-art.html";
ix++;
qfilename[ix] = "conservatives-and-progressives.html";
ix++;
qfilename[ix] = "generosity-among-the-rich.html";
ix++;
qfilename[ix] = "mysticism-has-kept-men-sane.html";
ix++;
qfilename[ix] = "taking-a-fence-down.html";
ix++;
qfilename[ix] = "the-cause-which-is-blocking-all-progress.html";
ix++;
qfilename[ix] = "the-center-of-every-mans-existence-is-a-dream.html";
ix++;
qfilename[ix] = "the-difference-between-construction-and-creation.html";
ix++;
qfilename[ix] = "this-dazed-and-dramatic-ignorance.html";
ix++;
qfilename[ix] = "we-are-in-eden-still.html";
ix++;
qfilename[ix] = "symbolic-language.html";
ix++;
qfilename[ix] = "democracy-is-worst-form-of-government.html";
ix++;
qfilename[ix] = "liberalism-is-not-socialism.html";
ix++;
qfilename[ix] = "we-are-doing-our-best.html";
ix++;
qfilename[ix] = "deeper-convictions-of-the-heart.html";
ix++;
qfilename[ix] = "the-divine-gift-of-purely-nonsensical-speech-and-action.html";
ix++;
qfilename[ix] = "evolutionary-drive-towards-complexity.html";
ix++;
qfilename[ix] = "belief-in-impossible-things.html";
ix++;
qfilename[ix] = "thnk-globally-act-locally.html";
ix++;
qfilename[ix] = "a-happy-man.html";
ix++;
qfilename[ix] = "moral-religion.html";
ix++;
qfilename[ix] = "only-a-human-being.html";
ix++;
qfilename[ix] = "simplicity-and-complexity.html";
ix++;
qfilename[ix] = "the-mysterious.html";
ix++;
qfilename[ix] = "the-supreme-goal-of-all-theory.html";
ix++;
qfilename[ix] = "this-highest-kind-of-religious-feeling.html";
ix++;
qfilename[ix] = "to-give-in-the-same-measure.html";
ix++;
qfilename[ix] = "violent-opposition-from-mediocre-minds.html";
ix++;
qfilename[ix] = "a-foolish-consistency.html";
ix++;
qfilename[ix] = "the-time-worn-yoke-of-their-opinions.html";
ix++;
qfilename[ix] = "a-first-rate-intelligence.html";
ix++;
qfilename[ix] = "faster-horses.html";
ix++;
qfilename[ix] = "only-connect.html";
ix++;
qfilename[ix] = "the-rainbow-bridge.html";
ix++;
qfilename[ix] = "wriggling.html";
ix++;
qfilename[ix] = "every-body-cries-a-union-is-absolutely-necessary.html";
ix++;
qfilename[ix] = "by-gifts-one-makes-slaves.html";
ix++;
qfilename[ix] = "conventional-views.html";
ix++;
qfilename[ix] = "prime-training-for-permanent-underclasses.html";
ix++;
qfilename[ix] = "climate-changers.html";
ix++;
qfilename[ix] = "successful-planning.html";
ix++;
qfilename[ix] = "thinkings-a-dizzy-business.html";
ix++;
qfilename[ix] = "authentic-cultures.html";
ix++;
qfilename[ix] = "consistency-is-the-playground-of-dull-mind.html";
ix++;
qfilename[ix] = "cultures-as-a-kind-of-mental-infection.html";
ix++;
qfilename[ix] = "evolutionary-success-and-individual-suffering.html";
ix++;
qfilename[ix] = "from-a-biological-perspective-nothing-is-unnatural.html";
ix++;
qfilename[ix] = "history-is-something-very-few-people-have-been-doing.html";
ix++;
qfilename[ix] = "human-imagination-more-than-biological-reality.html";
ix++;
qfilename[ix] = "most-sociopolitical-hierarchies-lack-a-logical-or-biological-basis.html";
ix++;
qfilename[ix] = "myths-are-stronger-than-anyone-could-have-imagined.html";
ix++;
qfilename[ix] = "no-single-natural-way-of-life-for-sapiens.html";
ix++;
qfilename[ix] = "these-principles-have-no-objective-validity.html";
ix++;
qfilename[ix] = "unprecedented-growth-in-human-power.html";
ix++;
qfilename[ix] = "the-change-dilemma.html";
ix++;
qfilename[ix] = "daily-acts-of-trivia.html";
ix++;
qfilename[ix] = "the-other-side-of-complexity.html";
ix++;
qfilename[ix] = "the-inner-life-of-the-artist.html";
ix++;
qfilename[ix] = "torturing-the-data.html";
ix++;
qfilename[ix] = "merely-a-muddle.html";
ix++;
qfilename[ix] = "ignorant-and-free.html";
ix++;
qfilename[ix] = "unintelligible-propositions.html";
ix++;
qfilename[ix] = "little-things-seen-largely.html";
ix++;
qfilename[ix] = "good-management-is-like-the-beatles.html";
ix++;
qfilename[ix] = "life-can-be-much-broader.html";
ix++;
qfilename[ix] = "people-with-passion.html";
ix++;
qfilename[ix] = "technology-married-with-the-humanities.html";
ix++;
qfilename[ix] = "the-underlying-principle-of-the-problem.html";
ix++;
qfilename[ix] = "we-have-wonderful-arguments.html";
ix++;
qfilename[ix] = "where-the-puck-is-going-to-be.html";
ix++;
qfilename[ix] = "steve-jobs-ideals.html";
ix++;
qfilename[ix] = "the-fragile-constructs-of-history.html";
ix++;
qfilename[ix] = "when-you-can-measure-what-you-are-speaking-about.html";
ix++;
qfilename[ix] = "the-extent-of-freedom-in-all-of-its-dimensions.html";
ix++;
qfilename[ix] = "national-parks-and-reserves.html";
ix++;
qfilename[ix] = "the-discomfort-of-thought.html";
ix++;
qfilename[ix] = "the-golden-eternity.html";
ix++;
qfilename[ix] = "ends-for-which-we-live.html";
ix++;
qfilename[ix] = "single-garment-of-destiny.html";
ix++;
qfilename[ix] = "ten-thousand-fools-proclaim-themselves.html";
ix++;
qfilename[ix] = "the-arc-of-history.html";
ix++;
qfilename[ix] = "unarmed-truth-and-unconditional-love.html";
ix++;
qfilename[ix] = "critical-thinking-followed-by-action.html";
ix++;
qfilename[ix] = "equals.html";
ix++;
qfilename[ix] = "more-popular-than-jesus.html";
ix++;
qfilename[ix] = "the-enormous-extension-of-our-being.html";
ix++;
qfilename[ix] = "labor-is-the-superior-of-capital.html";
ix++;
qfilename[ix] = "introduction-of-a-new-order-of-things.html";
ix++;
qfilename[ix] = "balance-is-required-to-maintain-democracy.html";
ix++;
qfilename[ix] = "inextricably-linked-in-freedom.html";
ix++;
qfilename[ix] = "integrity-and-conviction.html";
ix++;
qfilename[ix] = "the-challenge-of-swing.html";
ix++;
qfilename[ix] = "the-love-of-what-we-are-doing.html";
ix++;
qfilename[ix] = "the-philosophy-of-jazz.html";
ix++;
qfilename[ix] = "the-power-of-art.html";
ix++;
qfilename[ix] = "the-undisputed-sovereignty-of-the-human-being.html";
ix++;
qfilename[ix] = "a-book-is-a-mans-best-friend.html";
ix++;
qfilename[ix] = "the-original-naivet.html";
ix++;
qfilename[ix] = "the-ultimate-democracy.html";
ix++;
qfilename[ix] = "changing-the-world.html";
ix++;
qfilename[ix] = "quality-of-children-vs-quantity.html";
ix++;
qfilename[ix] = "easy-solutions.html";
ix++;
qfilename[ix] = "every-third-american.html";
ix++;
qfilename[ix] = "we-must-respect-the-other-fellows-religion.html";
ix++;
qfilename[ix] = "intellectual-debate.html";
ix++;
qfilename[ix] = "enemies-of-art-and-artist.html";
ix++;
qfilename[ix] = "this-dear-fucked-up-planet.html";
ix++;
qfilename[ix] = "we-all-derive-from-the-same-source.html";
ix++;
qfilename[ix] = "quality-matters.html";
ix++;
qfilename[ix] = "hard-discipline-of-reasonableness-and-honesty.html";
ix++;
qfilename[ix] = "first-they-came.html";
ix++;
qfilename[ix] = "a-return-to-these-truths.html";
ix++;
qfilename[ix] = "the-makers-of-things.html";
ix++;
qfilename[ix] = "the-third-place.html";
ix++;
qfilename[ix] = "politics-and-the-debasement-of-language.html";
ix++;
qfilename[ix] = "the-web-of-life.html";
ix++;
qfilename[ix] = "freedom-of-expression-in-business.html";
ix++;
qfilename[ix] = "a-progressive-annual-tax-on-capital.html";
ix++;
qfilename[ix] = "postels-law.html";
ix++;
qfilename[ix] = "ism-mania.html";
ix++;
qfilename[ix] = "that-magical-honeycomb-of-words.html";
ix++;
qfilename[ix] = "the-world-is-a-wonderfully-weird-place.html";
ix++;
qfilename[ix] = "unbelievable-heroes.html";
ix++;
qfilename[ix] = "great-minds-discuss-ideas.html";
ix++;
qfilename[ix] = "men-fear-thought.html";
ix++;
qfilename[ix] = "ten-commandments-for-teachers.html";
ix++;
qfilename[ix] = "the-celestial-teapot.html";
ix++;
qfilename[ix] = "apes-and-humans.html";
ix++;
qfilename[ix] = "chimps-and-humans.html";
ix++;
qfilename[ix] = "to-prolong-our-presence-on-the-face-of-the-earth.html";
ix++;
qfilename[ix] = "progress-depends-on-retentiveness.html";
ix++;
qfilename[ix] = "only-two-sources-of-real-wealth.html";
ix++;
qfilename[ix] = "small-and-obscure-deeds.html";
ix++;
qfilename[ix] = "learning-from-experience.html";
ix++;
qfilename[ix] = "espn-president-meets-steve-jobs.html";
ix++;
qfilename[ix] = "i-dream-things-that-never-were.html";
ix++;
qfilename[ix] = "progress-depends-on-the-unreasonable-man.html";
ix++;
qfilename[ix] = "when-his-salary-depends-on-his-not-understanding-it.html";
ix++;
qfilename[ix] = "freedom-of-judgment.html";
ix++;
qfilename[ix] = "notions-to-explain-nature.html";
ix++;
qfilename[ix] = "a-long-conversation.html";
ix++;
qfilename[ix] = "the-trick-in-keeping-bands-together.html";
ix++;
qfilename[ix] = "the-columbia-disaster.html";
ix++;
qfilename[ix] = "the-credibility-of-a-comedian.html";
ix++;
qfilename[ix] = "a-work-ethic-gone-mad.html";
ix++;
qfilename[ix] = "preparing-managers-to-manage.html";
ix++;
qfilename[ix] = "relieving-ignorance.html";
ix++;
qfilename[ix] = "do-the-right-thing.html";
ix++;
qfilename[ix] = "dreams-come-true.html";
ix++;
qfilename[ix] = "myth-makers.html";
ix++;
qfilename[ix] = "god-and-morality.html";
ix++;
qfilename[ix] = "monkeys-with-money-and-guns.html";
ix++;
qfilename[ix] = "a-coke-is-a-coke.html";
ix++;
qfilename[ix] = "those-sharp-scratchy-harsh-almost-unpleasant-guys.html";
ix++;
qfilename[ix] = "shareholder-value.html";
ix++;
qfilename[ix] = "the-art-of-progress.html";
ix++;
qfilename[ix] = "the-loftiest-and-purest-art.html";
ix++;
qfilename[ix] = "all-the-worlds-cultures-now-available-to-us.html";
ix++;
qfilename[ix] = "an-integral-god.html";
ix++;
qfilename[ix] = "art-and-spirit.html";
ix++;
qfilename[ix] = "everybody-has-some-important-pieces-of-the-truth.html";
ix++;
qfilename[ix] = "homophobia.html";
ix++;
qfilename[ix] = "levels-of-development.html";
ix++;
qfilename[ix] = "the-beautiful-the-good-and-the-true.html";
ix++;
qfilename[ix] = "the-left-hand-dimension.html";
ix++;
qfilename[ix] = "a-planet-sized-problem.html";
ix++;
qfilename[ix] = "the-most-dangerous-of-devotions.html";
ix++;
qfilename[ix] = "the-real-problem-of-humanity.html";
ix++;
qfilename[ix] = "the-toxic-mix-of-religion-and-tribalism.html";
ix++;
qfilename[ix] = "true-character.html";
ix++;
qfilename[ix] = "lean.html";
ix++;
qfilename[ix] = "price-of-success.html";
ix++;
var max = ix;

var now = new Date();
var seed = now.getTime() % 0xffffffff;

function rand(n) {
  seed = (0x015a4e35 * seed) % 0x7fffffff;
  return (seed >> 16) % n;
}

function setContent(n) {
  var thisURL = document.URL;
  var blogIx = thisURL.indexOf("/blog/");
  var tagsIx = thisURL.indexOf("/tags/");
  var quotesIx = thisURL.indexOf("/quotes/");
  var coreIx = thisURL.indexOf("/core/");
  var intoIx = thisURL.indexOf("/intro/");
  var page = qfilename[n];
  if (blogIx > 0) {
    page = "../../quotes/" + page;
  }
  else
  if (tagsIx < 0 && quotesIx < 0 && coreIx < 0 && introIx < 0) {
    page = "quotes/" + page;
  } else {
    page = "../quotes/" + page;
  }
  window.location.replace(page);
}

function randomQuote() {
  rq = rand(max);
  if (rq < 0) {
    rq = 0;
  }
  if (rq >= max) {
    rq = max - 1;
  }
  setContent (rq);
}

function firstQuote() {
  var ix = 0;
  setContent(ix);
}

function lastQuote() {
  var ix = max - 1;
  setContent(ix);
}

function nextQuote() {
  bumpQuote(1);
}

function priorQuote() {
  bumpQuote(-1);
}

function bumpQuote(inc) {
  var thisURL = document.URL;
  var lastSlash = thisURL.lastIndexOf("/");
  var thisPage = thisURL.substr(lastSlash + 1);
  var ix = 0;
  var found = false;
  while (ix < max && (! found)) {
    var page = qfilename[ix];
    if (thisPage == page) {
      found = true;
    } else {
      ix++;
    }
  }
  if (found) {
    ix = ix + inc;
    if (ix >= max) {
      ix = 0;
    }
    if (ix < 0) {
      ix = max - 1;
    }
    setContent(ix);
  } else {
    setContent(0);
  }
}
